language: node_js
node_js:
  - "stable"
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod --bh /projet_font_end/
  - ng serve --host=0.0.0.0 --disable-host-check
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master